spring:
  application:
    name: KnowledgeBaseOfDubbo

server:
  port: 8080

dubbo:
  application:
    name: demo-jdp-provider
  provider:
    token: false
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://nacos-test-fs.inshopline.com:6801?namespace=test